id: MDE SIEM ingestion - Get Incident Data
version: -1
contentitemexportablefields:
  contentitemfields: {}
name: MDE SIEM ingestion - Get Incident Data
description: |-
  This playbook is part of the 'Malware Investigation And Response' pack. For more information, refer to https://xsoar.pan.dev/docs/reference/packs/malware-investigation-and-response.
  This playbook handles incident ingestion from a SIEM. The user provides the incident fields containing the alert ID. This playbook also enables changing the severity according to a user-defined scale to override the default assigned severity.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 52e83efb-9923-48db-8890-154683292a27
    type: start
    task:
      id: 52e83efb-9923-48db-8890-154683292a27
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 80
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 530df6d7-a01c-4b27-8f01-523aea5b33c6
    type: regular
    task:
      id: 530df6d7-a01c-4b27-8f01-523aea5b33c6
      version: -1
      name: Set Severity
      description: commands.local.cmd.set.incident
      script: Builtin|||setIncident
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      severity:
        complex:
          root: MsGraph.Alert
          accessor: Severity
          transformers:
          - operator: MapValuesTransformer
            args:
              input_values:
                value:
                  simple: inputs.ScaleToSetSeverity
                iscontext: true
              mapped_values:
                value:
                  simple: inputs.SeverityValuesMapping
                iscontext: true
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 230,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: abfe1ac1-44d2-462b-8a34-4990fae8643d
    type: title
    task:
      id: abfe1ac1-44d2-462b-8a34-4990fae8643d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: e5e4cdd0-04b3-49e8-8278-95600c0dc574
    type: condition
    task:
      id: e5e4cdd0-04b3-49e8-8278-95600c0dc574
      version: -1
      name: Is override SIEM severity enabled?
      description: Is override SIEM severity enabled?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      Override:
      - "5"
    separatecontext: false
    conditions:
    - label: Override
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.OverrideSIEMSeverity
            iscontext: true
          right:
            value:
              simple: "true"
          ignorecase: true
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.ScaleToSetSeverity
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.SeverityValuesMapping
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: a83d69bf-8a57-42b1-84eb-6c310a20cb15
    type: title
    task:
      id: a83d69bf-8a57-42b1-84eb-6c310a20cb15
      version: -1
      name: Override Severity
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: 58a75d6e-dcde-4c5f-8487-6057e53de565
    type: regular
    task:
      id: 58a75d6e-dcde-4c5f-8487-6057e53de565
      version: -1
      name: Get full alert details
      description: Get details for a specific alert.
      script: '|||msg-get-alert-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      alert_id:
        simple: ${inputs.SIEMincidentFieldForID}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {
      "22_12_#default#": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 865,
        "width": 630,
        "x": 230,
        "y": 80
      }
    }
  }
inputs:
- key: SIEMincidentFieldForID
  value:
    simple: ${incident.externalsystemid}
  required: false
  description: The name of the incident field that contains the detection ID or incident ID.
  playbookInputQuery:
- key: ScaleToSetSeverity
  value:
    simple: Informational,Low,Medium,High
  required: false
  description: "The severity scale as represented in the EDR. \nFor example, in Microsoft Defender for Endpoint the severity scale is Informational, Low, Medium, High."
  playbookInputQuery:
- key: SeverityValuesMapping
  value:
    simple: 0.5, 1, 2, 3
  required: false
  description: |-
    "The mapping to Cortex XSOAR severity from the severity scale in the EDR (the ScaleToSetSeverity inputs).
    For example
    0.5, 1, 2, 3,4
    Possible values to use are 0,0.5, 1, 2, 3,4
    Which represent Unknown, Informational, Low, Medium, High, Critical
  playbookInputQuery:
- key: OverrideSIEMSeverity
  value:
    simple: "False"
  required: false
  description: Whether to set the severity according to the ScaleToSetSeverity and SeverityValuesMapping settings (True) or keep the original severity as mapped by the SIEM (False).
  playbookInputQuery:
outputs:
- contextPath: CrowdStrike.Detection.Behavior.FileName
  description: The file name of the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.Scenario
  description: The scenario name of the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.MD5
  description: The MD5 hash of the IOC of the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.SHA256
  description: The SHA256 hash of the IOC of the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.IOCType
  description: The type of the IOC.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.IOCValue
  description: The value of the IOC.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.CommandLine
  description: The command line executed in the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.UserName
  description: The user name related to the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.SensorID
  description: The sensor ID related to the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.ParentProcessID
  description: The ID of the parent process.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.ProcessID
  description: The process ID of the behavior.
  type: string
- contextPath: CrowdStrike.Detection.Behavior.ID
  description: The ID of the behavior.
  type: string
- contextPath: CrowdStrike.Detection.System
  description: The system name of the detection.
  type: string
- contextPath: CrowdStrike.Detection.CustomerID
  description: The ID of the customer (CID).
  type: string
- contextPath: CrowdStrike.Detection.MachineDomain
  description: The name of the domain of the detection machine.
  type: string
- contextPath: CrowdStrike.Detection.ID
  description: The detection ID.
  type: string
- contextPath: CrowdStrike.Detection.ProcessStartTime
  description: The start time of the process that generated the detection.
  type: string
- contextPath: Endpoint
  description: The details of the endpoint.
  type: string
fromversion: 6.5.0
tests:
 -  No tests
marketplaces:
- xsoar