
default:
  image: ${DOCKER_IO}/devdemisto/gitlab-content-ci:1.0.0.64455
  artifacts:
    expire_in: 30 days
    paths:
      - ${CI_PROJECT_DIR}/artifacts/*
      - ${CI_PROJECT_DIR}/pipeline_jobs_folder/*
    when: always

stages:
  - Test RIT
  - Upload
  - Release
  - Publish
  - sync-buckets
  - are-jobs-really-done
  - fan-in  # concentrate pipeline artifacts to a single job before triggering child slack pipeline.

include:
  - local: .gitlab/ci/rit-ci/.gitlab-ci.variables.yml
  - local: .gitlab/ci/rit-ci/.gitlab-ci.workflow.yml
  - local: .gitlab/ci/rit-ci/.gitlab-ci.global.yml
  - local: .gitlab/ci/rit-ci/.gitlab-ci.on-push.yml
  - local: .gitlab/ci/rit-ci/.gitlab-ci.bucket-upload.yml
  - local: .gitlab/ci/gitlab-ci.shared.variables.yml
