repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.272
  hooks:
  - id: ruff
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
  - id: check-yaml
    exclude: ./.gitlab
  - id: check-ast
  - id: check-merge-conflict
  - id: debug-statements
    language_version: python3
  - id: name-tests-test
    files: .+_test.py$
  - id: trailing-whitespace
  - id: check-toml
  - id: check-xml
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.2
  hooks:
  - id: poetry-check
    args:
    - --lock
    files: ^pyproject.toml$
- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
  - id: pycln
    args:
    - --all
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.982
#   hooks:
#   - id: mypy
#     additional_dependencies:
#     - types-PyYAML
#     - types-paramiko
#     - types-python-dateutil
#     - types-pytz
#     - types-requests
#     - types-setuptools
#     - types-tabulate
#     - types-ujson
#     args:
#     - --ignore-missing-imports
#     - --check-untyped-defs
#     - --show-error-codes
#     - --follow-imports=silent
#     - --allow-redefinition
#     exclude: infrastructure_tests/tests_data|Utils/test_upload_flow
# - repo: https://github.com/charliermarsh/ruff-pre-commit
#   rev: v0.0.272
#   hooks:
#   - id: ruff
#     parallel: false
#     min_py_version: '3.7'
#     args:
#     - --fix
# - repo: local
#   hooks:
#   - id: pytest
#     name: pytest
#     entry: poetry run pytest
#     files:  _test\.py$
#     language: system
#     types: [python]
#     pass_filenames: false
#     always_run: true