repos:
- repo: local
  hooks:
    - id: mdx-validation
      name: Validate README.md with MDX
      entry: node .hooks/validate-mdx.js
      language: node
      files: "^(.*/)?README\\.md$"
      require_serial: true
      additional_dependencies: #match package-lock of content docs
        - "@mdx-js/mdx@1.6.22"
        - "fs-extra@9.1.0"

#- repo: https://github.com/igorshubovych/markdownlint-cli
#  rev: v0.36.0  # Check for the latest version
#  hooks:
#    - id: markdownlint
#      files: \.md$
#      args: ["--config", ".markdownlint.json"]
#
