repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.5.2
  hooks:
  - id: ruff
    args:
    - --fix
    exclude: CommonServerPython.py
  - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
  - id: check-yaml
    exclude: .gitlab
  - id: check-ast
  - id: check-merge-conflict
#  - id: debug-statements
#    language_version: python3
  - id: name-tests-test
    files: .+_test.py$
  - id: trailing-whitespace
  - id: check-toml
  - id: check-xml
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.3
  hooks:
  - id: poetry-check
    args:
    - --lock
    files: ^pyproject.toml$
- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
  - id: pycln
    args:
    - --all
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    entry: mypy
    args:
    - --show-error-codes
    additional_dependencies:
      - types-requests
      - types-paramiko
      - types-PyYAML
      - types-setuptools
      - types-ujson
      - types-decorator
      - types-retry
      - types-pytz
      - types-python-dateutil
      - types-tabulate
      - types-dateparser
      - types-pkg-resources
    types: [python]
    #duplicate here and in pyproject.toml because https://github.com/python/mypy/issues/13916
    exclude: BlacklistValidation*|SecretActions*|artifacts*|.*infrastructure_tests*|.*_test|test_.*|test_data|tests_data|.venv
