repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.272
  hooks:
  - id: ruff
    exclude: CommonServerPython.py
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-json
  - id: check-yaml
    exclude: .gitlab
  - id: check-ast
  - id: check-merge-conflict
#  - id: debug-statements
#    language_version: python3
  - id: name-tests-test
    files: .+_test.py$
  - id: trailing-whitespace
  - id: check-toml
  - id: check-xml
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.2
  hooks:
  - id: poetry-check
    args:
    - --lock
    files: ^pyproject.toml$
- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
  - id: pycln
    args:
    - --all
