exclude: .devcontainer/|.vscode|Pipfile.lock|.gitlab/ci/|docs
files: ''
repos:
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.17.2
  hooks:
    - id: markdownlint-cli2
      files: "^(.*/)?README\\.md$"
      args: [ "--config", ".markdownlint-cli2.jsonc" ]
      exclude: Packs/ReversingLabs_Titanium_Cloud/Integrations/ReversingLabsTitaniumCloudv2/README\.md