variables:
  WORKFLOW_PIPELINE_NAME: 'Pipeline for branch: $CI_COMMIT_REF_NAME'

workflow:
  name: '$WORKFLOW_PIPELINE_NAME'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        WORKFLOW_PIPELINE_NAME: 'Merge request #$CI_MERGE_REQUEST_IID pipeline for branch $CI_COMMIT_REF_NAME to $CI_MERGE_REQUEST_TARGET_BRANCH_NAME'

    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/ && $CI_COMMIT_REF_NAME != "master"'
      variables:
        WORKFLOW_PIPELINE_NAME: 'Merge request for branch:$CI_COMMIT_REF_NAME pipeline'

    - if: '$CI_PIPELINE_SOURCE =~ /^(push|contrib)$/ && $CI_COMMIT_REF_NAME != "master"'
      variables:
        WORKFLOW_PIPELINE_NAME: 'Merge to master pipeline'

    - if: '$IS_NIGHTLY == "true" && $CI_PIPELINE_SOURCE == "schedule"'
      variables:
        WORKFLOW_PIPELINE_NAME: 'Scheduled Content Docs Nightly pipeline for branch: $CI_COMMIT_REF_NAME'

    - if: '$IS_NIGHTLY == "true" && $CI_PIPELINE_SOURCE != "schedule"'
      variables:
        WORKFLOW_PIPELINE_NAME: 'Triggered Content Docs Nightly pipeline for branch: $CI_COMMIT_REF_NAME'

    # Don't add any other rules after this one.
    - when: always  # Other pipelines can run, but use the default name
