
default:
  image: ${DOCKER_IO}/devdemisto/gitlab-content-ci:1.0.0.64455
  artifacts:
    expire_in: 30 days
    paths:
      - ${CI_PROJECT_DIR}/artifacts/*
      - ${CI_PROJECT_DIR}/pipeline_jobs_folder/*
    when: always

stages:
  - build-docs
  - are-jobs-really-done
  - fan-in  # concentrate pipeline artifacts to single job before triggering child slack pipeline

include:
  - local: .gitlab/ci/content-docs/.gitlab-ci.variables.yml
  - local: .gitlab/ci/content-docs/.gitlab-ci.workflow.yml
  - local: .gitlab/ci/content-docs/.gitlab-ci.global.yml
  - local: .gitlab/ci/content-docs/.gitlab-ci.on-push.yml
  - local: .gitlab/ci/gitlab-ci.shared.variables.yml
