name: MDX Validation

on: [pull_request]

jobs:
  validate-mdx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Get Changed Files
        id: changed-files
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} -- '*.md')
          echo "FILES<<EOF" >> $GITHUB_ENV
          echo "$FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Validate MDX for Changed README.md Files
        run: |
          NO_HTML="# NO_HTML"
          YES_HTML="# YES_HTML"

          is_html_doc() {
              grep -qE "^($YES_HTML|<p>|<!DOCTYPE html>|<thead>.*<tbody>)" "$1"
          }

          FILES_TO_VALIDATE=()

          for file in $FILES; do
              if [[ $(basename "$file") == "README.md" ]] && ! is_html_doc "$file"; then
                  FILES_TO_VALIDATE+=("$file")
              fi
          done

          if [[ ${#FILES_TO_VALIDATE[@]} -eq 0 ]]; then
              echo "✅ No eligible README.md files changed in PR."
              exit 0
          fi

          echo "Running MDX validation on changed files..."

          for file in "${FILES_TO_VALIDATE[@]}"; do
              node --input-type=module - "$file" <<'EOF'
              import { readFileSync } from 'fs';
              import { compile } from '@mdx-js/mdx';

              const file = process.argv[1];

              try {
                  const contents = readFileSync(file, 'utf8');
                  await compile(contents);
                  console.log(`✅ MDX validation passed: ${file}`);
              } catch (error) {
                  console.error(`❌ MDX validation failed: ${file}\n`, error.message);
                  process.exit(1);
              }
              EOF
          done
