name: Validate README.md with MDX

on:
  pull_request:
    paths:
      - '**/README.md'

jobs:
  validate-mdx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install commander fs-extra @mdx-js/mdx

      - name: Validate README.md files
        run: |
          for file in $(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep 'README.md'); do
            echo "Validating $file"
            node - << 'EOF'
          const cli = require('commander');
          const { readFile } = require('fs-extra');
          const mdx = require('@mdx-js/mdx');

          async function parseMDX(file) {
              const contents = await readFile(file, 'utf8');
              parsed = await mdx(contents);
              console.log(`${parsed}`);
          }

          const file = process.argv[2];
          parseMDX(file).catch((reason) => {
              console.error(reason);
              process.exit(1);
          });
          EOF
          done