name: MDX Validation

on: [pull_request]

jobs:
  validate-mdx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Validate MDX for README.md files
        run: |
          NO_HTML="# NO_HTML"
          YES_HTML="# YES_HTML"

          is_html_doc() {
              grep -qE "^($YES_HTML|<p>|<!DOCTYPE html>|<thead>.*<tbody>)" "$1"
          }

          FILES_TO_VALIDATE=()

          for file in $(git ls-files '*.md'); do
              if [[ $(basename "$file") == "README.md" ]] && ! is_html_doc "$file"; then
                  FILES_TO_VALIDATE+=("$file")
              fi
          done

          if [[ ${#FILES_TO_VALIDATE[@]} -eq 0 ]]; then
              echo "✅ No eligible README.md files found for MDX validation."
              exit 0
          fi

          echo "Running MDX validation..."

          export FILES_TO_VALIDATE_JSON=$(printf '%s\n' "${FILES_TO_VALIDATE[@]}" | jq -R . | jq -s .)

          node --input-type=module - <<'EOF'
          import { readFileSync } from 'fs';
          import { compile } from '@mdx-js/mdx';

          const files = JSON.parse(process.env.FILES_TO_VALIDATE_JSON);

          for (const file of files) {
              try {
                  const contents = readFileSync(file, 'utf8');
                  await compile(contents);
                  console.log(`✅ MDX validation passed: ${file}`);
              } catch (error) {
                  console.error(`❌ MDX validation failed: ${file}\n`, error.message);
                  process.exit(1);
              }
          }
          EOF
