.trigger-contribution-build-role:
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /^(schedule|trigger)$/ && $TRIGGER_CONTRIBUTION_BUILD == "true"'

stages:
  - trigger-contribution-build

trigger-contribution-build:
  stage: trigger-contribution-build
  variables:
    WORKFLOW: 'Trigger contribution build'
  extends:
    - .trigger-contribution-build-role
    - .default-job-settings
  script:
    - pip install PyGithub python-gitlab coloredlogs demisto_sdk
    - python3 ./Utils/trigger_contribution_build.py --github-token "${GITHUB_TOKEN}" --gitlab-api-token "${GITLAB_API_TOKEN}" --gitlab-trigger-token "${TRIGGER_CONTRIBUTION}"