default:
  image: ${DOCKER_IO}/devdemisto/gitlab-content-ci:1.0.0.64455
  artifacts:
    expire_in: 30 days
    paths:
      - ${CI_PROJECT_DIR}/artifacts/*
      - ${CI_PROJECT_DIR}/pipeline_jobs_folder/*
    when: always

include:
  - file: .gitlab/ci/global.yml
    ref: $CI_COMMIT_REF_NAME
    project: "${CI_PROJECT_NAMESPACE}/infra"
  - file: .gitlab/ci/variables.yml
    ref: $CI_COMMIT_REF_NAME
    project: "${CI_PROJECT_NAMESPACE}/infra"

.before-script-slack-notify:
  before_script:
    - source .gitlab/helper_functions.sh
    - !reference [.setup-network-certs]
    - !reference [.poetry-install]
    - !reference [.granting_execute_permissions_on_files]
    - !reference [.setup-artifactory]
    - !reference [.create_artifacts_folder]
    - !reference [.create-artifacts-repositories-folder]
    - !reference [.clone-content-test-conf]

stages:
  - notify

slack-notify:
  tags:
    - gke
  stage: notify
  needs:
    - pipeline: $PIPELINE_TO_QUERY
      job: $JOB_NAME
  extends:
    - .before-script-slack-notify
  script:
    - env
    - |
      SLACK_ARGS=()
      if [ -n "${SLACK_MSG_FILE}" ]; then
        SLACK_ARGS+=("--file" "${SLACK_MSG_FILE}")
      fi
      if [ -n "${SLACK_MSG_ATTACHMENTS}" ]; then
        SLACK_ARGS+=("--attachments" "${SLACK_MSG_ATTACHMENTS}")
      fi
      if [ -n "${SLACK_MSG_THREAD}" ]; then
        SLACK_ARGS+=("--thread" "${SLACK_MSG_THREAD}")
      fi
      if [ -n "${TARGET_HOUR}" ]; then
        SLACK_ARGS+=("--target_hours" "${TARGET_HOUR}")
      fi
      if [ -n "${TARGET_MINUTES}" ]; then
        SLACK_ARGS+=("--target_minutes" "${TARGET_MINUTES}")
      fi
      if [ -n "${WINDOW_MINUTES}" ]; then
        SLACK_ARGS+=("--window_minutes" "${WINDOW_MINUTES}")
      fi
      poetry run python3 -u ./Tests/scripts/gitlab_slack_notifier.py -p "${PIPELINE_TO_QUERY}" -s "${SLACK_TOKEN}" -c "${GITLAB_STATUS_TOKEN}" -ch "${SLACK_CHANNEL}" -tw "${WORKFLOW}"  --allow-failure "${SLACK_ALLOW_FAILURE}" --name-mapping_path "${CI_PROJECT_DIR}/config/name_mapping.json" "${SLACK_ARGS[@]}"
  retry:
    max: 2
